name: SimpleCrates
version: 1.0.0
author: WavyCraft
api: 5.0.0
main: wavycraft\simplecrates\Loader

permissions:
  simplecrates.key:
    default: op
  simplecrates.keyall:
    default: op
  simplecrates.createcrate:
    default: op
  simplecrates.removecrate:
    default: op
